### PR TITLE
Extend GeneralSign equipment type

### PR DESCRIPTION
**Pull request by culka**
Include fields for:
- number of frames
- replaces rail
- main line
- line signage

Also implement the note field for generic equipment, which was not used before.

Resolves https://github.com/HSLdevcom/jore4/issues/1717

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13)

### CODE REVIEW

**Review by Leitsi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13#-:-NtyjlIJ1xlyxwIwgOZU:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved

___
*[`src/main/java/org/rutebanken/tiamat/model/Equipment_VersionStructure.java` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13#-NtyjnktEmaTiVHqSLeJ:-NtyjnktEmaTiVHqSLeK:bhzqrrz) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/7de35344e2501cdb35d668483efd4143e8b03225/src/main/java/org/rutebanken/tiamat/model/Equipment_VersionStructure.java#L53)):*
> ```Java
>             @AttributeOverride(name = "lang", column = @Column(name = "note_lang"))
>     })
>     @Embedded
> ```

I don't quite grasp what is going on here or why this needs to be done :shrug:

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`src/main/java/org/rutebanken/tiamat/model/Equipment_VersionStructure.java` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13#-NtyjnktEmaTiVHqSLeJ:-NtzJESw85bC1ci1eTuy:blmg50i) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/7de35344e2501cdb35d668483efd4143e8b03225/src/main/java/org/rutebanken/tiamat/model/Equipment_VersionStructure.java#L53)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't quite grasp what is going on here or why this needs to be done :shrug:
</blockquote></details>

There is a pre-existing `note` field in the data model, but it was not persisted anywhere. This tells the Equipment how the note is stored in the database.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13)* status: 3 of 7 files reviewed, all discussions resolved

___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 1927 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13#-NtzL4_C98IBcka6cdCn:-NtzL4_C98IBcka6cdCo:undefined) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/5a653206279d1d31b38bb2e35022d5250eb07fc9/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L1927)):*
> ```Java
> 
>     @Test
>     public void testMutatePlaceEquipmentSignHSLValues   () throws Exception {
> ```





_Suggestion:_
```Java
    public void testMutatePlaceEquipmentSignHSLValues() throws Exception {
```

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 1927 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/13#-NtzL4_C98IBcka6cdCn:-NtzRQuh3Q6nWNXVLdec:bt2vr1b) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/5a653206279d1d31b38bb2e35022d5250eb07fc9/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L1927)):*
> ```Java
> 
>     @Test
>     public void testMutatePlaceEquipmentSignHSLValues   () throws Exception {
> ```

Fixed.

**Pull request merged**
