### PR TITLE
Save stop place topographic places by ref

### PR DESCRIPTION
**Pull request by culka**
Use a direct reference string when saving associated topographic places for stop places.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
There were no changes to the test code. The `GraphQLResourceStopPlaceIntegrationTest` class contains many integration tests. Have you gone through it, could you make a new test there or update an existing one?

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-:-Nvq2U6F47TBsXBOUhvC:b-dymbxr)* status: 0 of 2 files reviewed, all discussions resolved

**Review by culka — COMMENTED** [review]
There were no existing tests which modify or add a topographic place for a stop using GraphQL, I added some cases.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-:-Nvq7h5o62CFpd0OdYWT:b-8vvnxr)* status: 0 of 3 files reviewed, all discussions resolved

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 1990 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqEudNAwc6GO4oEnVn:-NvqEudNAwc6GO4oEnVo:b-22lbi) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L1990)):*
> ```Java
>     @Test
>     public void testCreateStopWithTopographicPlaceHSL() {
>         TopographicPlace topographicPlace = new TopographicPlace(new EmbeddableMultilingualString("countyforinstance", "lng"));
> ```

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 2024 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqF6M_0XbV6ah1qIBm:-NvqF6M_0XbV6ah1qIBn:b-22lbi) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L2024)):*
> ```Java
>     @Test
>     public void testCreateStopWithoutTopographicPlaceHSL() {
>         TopographicPlace topographicPlace = new TopographicPlace(new EmbeddableMultilingualString("countyforinstance", "lng"));
> ```

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 2050 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqF5Bm9JaWpHx6F6tp:-NvqF5Bm9JaWpHx6F6tq:b-22lbi) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L2050)):*
> ```Java
>     @Test
>     public void testMutateStopChangeTopographicPlaceHSL() {
>         TopographicPlace topographicPlaceOrigin = new TopographicPlace(new EmbeddableMultilingualString("original location", "lng"));
> ```

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 1990 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqEudNAwc6GO4oEnVn:-NvqGbfa1BnMoxH4dPLp:b-886gsx) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L1990)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.
</blockquote></details>

Fixed
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 2024 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqF6M_0XbV6ah1qIBm:-NvqGctsEt7IWxQgff2S:b-886gsx) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L2024)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.
</blockquote></details>

Fixed
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java` line 2050 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-NvqF5Bm9JaWpHx6F6tp:-NvqGaHmEijBt6yAtC6-:b-886gsx) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d7e1dece37ed4c2a88ea4074db07faf7f33b49f1/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java#L2050)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `lng` parameter should be replaced with some real language code like `fi`, `en` or `no`.
</blockquote></details>

Fixed

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/16#-:-NvqJRrS-BOOx-A_8i_o:bnfp4nl)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

**Pull request merged**
