### PR TITLE
Hsl shelter equipment additions

### PR DESCRIPTION
**Pull request by culka**
Add new properties needed by HSL for shelters.
- database migrations
- JPA model update
- GraphQL interface
- Tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java` line 3 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYqmLi1VPpN7kEH3BX:-NyYqmLi1VPpN7kEH3BY:undefined) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/874dac8b9341ff122cfd55606b1b8dd82e0248be/src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java#L3)):*
> ```Java
> package org.rutebanken.tiamat.model.hsl;
> 
> // Note: named with Hsl prefix to avoid colliding with StopTypeEnumeration
> ```





_Suggestion:_
```Java
// Note: named with Hsl prefix to avoid colliding with ShelterTypeEnumeration
```
___
*[`src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYrxYjBEWE7LwCcqGI:-NyYrxYjBEWE7LwCcqGJ:b-kjgndz) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/874dac8b9341ff122cfd55606b1b8dd82e0248be/src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java#L7)):*
> ```Java
>     GLASS("glass"),
>     STEEL("steel"),
>     POST("post"),
> ```

I might have preferred `pole` since it has less double meaning, but guess this will do as well.
___
*[`src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYrJo16DhP9NdsBHGI:-NyYrJo16DhP9NdsBHGJ:b-hu9yec) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/874dac8b9341ff122cfd55606b1b8dd82e0248be/src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java#L9)):*
> ```Java
>     POST("post"),
>     VIRTUAL("virtual"),
>     LEAVE_OFF("leaveOff");
> ```

This does sound a bit weird but let's maybe still leave as is and change when we know more details...
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java` line 153 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYtnjQ5K3ym0t89AVa:-NyYtnjQ5K3ym0t89AVb:bilb7t0) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/899cef001797e23b1b526c1558d9298ad7a28ed2/src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java#L153)):*
> ```Java
>     public static GraphQLEnumType mapTypeEnum = createCustomEnumType(MAP_TYPE, MapTypeEnumeration.class);
>     public static GraphQLEnumType pedestrianCrossingRampTypeEnum = createCustomEnumType(PEDESTRIAN_CROSSING_RAMP_TYPE, PedestrianCrossingRampTypeEnumeration.class);
>     public static GraphQLEnumType shelterType = createCustomEnumType(SHELTER_TYPE_ENUM, HslShelterTypeEnumeration.class);
> ```

This could maybe have `Enum` affix like other enum types here.



_Suggestion:_
```Java
public static GraphQLEnumType shelterTypeEnum = createCustomEnumType(SHELTER_TYPE_ENUM, HslShelterTypeEnumeration.class);
```

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java` line 3 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYqmLi1VPpN7kEH3BX:-Ny_0MoU98lWBh-BD1GS:b-5dh277) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/874dac8b9341ff122cfd55606b1b8dd82e0248be/src/main/java/org/rutebanken/tiamat/model/hsl/HslShelterTypeEnumeration.java#L3)):*
> ```Java
> package org.rutebanken.tiamat.model.hsl;
> 
> // Note: named with Hsl prefix to avoid colliding with StopTypeEnumeration
> ```

Removed comment as unnecessary after renaming.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java` line 153 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-NyYtnjQ5K3ym0t89AVa:-Ny_082I9UbmE5L3wd9l:b-pm83g0) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/899cef001797e23b1b526c1558d9298ad7a28ed2/src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java#L153)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This could maybe have `Enum` affix like other enum types here.
</blockquote></details>

Fixed this by renaming accesiibility shelter type into `ShelterWidthType` and new shelter type into `ShelterType`, enabling better names here.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-:-Ny_FIwD-8UQgwWNftWA:bnfp4nl)* status: 1 of 13 files reviewed, all discussions resolved

**Review by Leitsi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r5, 4 of 4 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 10 of 10 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/20#-:-Nyd7isCBht7cQIZD03z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
