### PR TITLE
Add Organisation data model and HSL specific Organisation relationships for Stop Places

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)

### CODE REVIEW

**Comment by niknii-vincit** [comment]
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/OrganisationUpdater.java` line 85 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-O2P3OlD4Enkzz-qOfSy:-O2P3OlD4Enkzz-qOfSz:b-7yvund) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/a47266a94f081520d3903c53a85d4c1fe9e2212f/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/OrganisationUpdater.java#L85)):*
> ```Java
>     }
> 
>     private boolean populateOrganisation(Map input, Organisation updatedOrganisation) {
> ```

To me this name is misleading somehow, took me a bit to understand what's going on :sweat_smile:, could it be something like `populateOrganisationWithUpdates` or `updateOrganisation`?

**Review by niknii-vincit — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 7 of 7 files at r2, 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)* status: 12 of 26 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Review by niknii-vincit — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 5 files at r4, 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)* status: 16 of 26 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Comment by niknii-vincit** [comment]
*[`src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-O2POpml59ih4zFhjOh3:-O2POpml59ih4zFhjOh4:bolppxh) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d418af79c57329cc774a8d912ca3a6ef7c93f397/src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java#L54)):*
> ```Java
>             List<Organisation> organisations = getAllVersionsOfOrganisation(organisationId);
> 
>             // TODO: would we need any authorization by role here?
> ```

Would probably be good, just in case :sweat_smile: Where/how would this be executed, in the Jore UI?

**Review by niknii-vincit — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 5 files at r4, 8 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

**Comment by niknii-vincit** [comment]
*[`src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-O2POpml59ih4zFhjOh3:-O2UXZ0t4cllnY5RdmG-:bxa0tx9) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d418af79c57329cc774a8d912ca3a6ef7c93f397/src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java#L54)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Absolutely no idea. Just noticed that some other services had some authorization logic here, see eg. https://github.com/HSLdevcom/jore4-tiamat/blob/main/src/main/java/org/rutebanken/tiamat/service/TariffZoneTerminator.java#L53
But not quite sure if we'd need anything like that for these entities, or what other changes would that even require.
</blockquote></details>

Yeah I'd make a ticket out of this to decide with Teemu whether it's worth doing later on.

**Review by niknii-vincit — APPROVED** [review]
:shipit: 

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-:-O2UZm7M4IbmVogYKpB3:bizlbj6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-O2POpml59ih4zFhjOh3:-O2ySFg03JdzK6ljKNwO:b-r0jpgs) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d418af79c57329cc774a8d912ca3a6ef7c93f397/src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java#L54)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Yeah I'd make a ticket out of this to decide with Teemu whether it's worth doing later on.
</blockquote></details>

Yeah we should use proper authorization here. Simple 
```
authorizationService.assertAuthorized(ROLE_ORGANISATION_EDIT, organisations);
```
should work here, auth integration will handle the roles, but for now everything is permitted.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)* status: 23 of 28 files reviewed, all discussions resolved (waiting on @culka and @niknii-vincit)

___
*[`src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-O2POpml59ih4zFhjOh3:-O37bKhE3o0EBapRNVuU:b5qx71v) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/d418af79c57329cc774a8d912ca3a6ef7c93f397/src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java#L54)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Yeah we should use proper authorization here. Simple 
```
authorizationService.assertAuthorized(ROLE_ORGANISATION_EDIT, organisations);
```
should work here, auth integration will handle the roles, but for now everything is permitted.
</blockquote></details>

Added :thumbsup:

**Review by culka — APPROVED** [review]
Looks really good!

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28#-:-O37gWM3-YCnDpK2RzFB:bm352jk)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
