### PR TITLE
Add group of stop places location and validity

### PR DESCRIPTION
**Pull request by culka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)

### CODE REVIEW

**Review by Huulivoide — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24#-O-oSLHeEh3GuSG8S0SL:-O-oSLHeEh3GuSG8S0SM:b5g5f5p) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/1bb49cb93b8f8efe76c22f7d7a14666ec1fb64a7/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java#L79)):*
> ```Java
> 
>     @Autowired
>     private ValidityUpdater validityUpdater;
> ```

Added, yet not used.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24#-O-oSLHeEh3GuSG8S0SL:-O-oekD84ky2YC39YU2S:ba3dfob) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/1bb49cb93b8f8efe76c22f7d7a14666ec1fb64a7/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java#L79)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Added, yet not used.
</blockquote></details>

Removed

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24#-O-og0hI4SnPsFK6qElk:-O-ohVsC31hYNLuoecg1:b-o59ca2) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/16cb31c12703a0a3f4668e5dd7a62c67471e6c42/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/GroupOfStopPlacesUpdater.java#L37)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Importit jäi vielä tänne
</blockquote></details>

Poistettu

**Review by Huulivoide — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
